version: "3.9"

services:
  postgres:
    container_name: hero_camp_db
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hero_camp
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prepare_postgres.sql:/docker-entrypoint-initdb.d/prepare_postgres.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: hero_camp_api
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: hero_camp
      DEBUG_MODE: 1
    ports:
      - 3000:3000
    volumes:
      - ..:/hero_camp:cached
    depends_on:
      postgres:
        condition: service_healthy
    command: /bin/bash -c "while sleep 1000; do :; done"

volumes:
  postgres_data:
    driver: local
